from fpdf import FPDF
import pandas as pd
from datetime import datetime
import re

class PDFReport(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'SiteMate Pro | Engineering Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by SiteMate Pro AI - Page {self.page_no()}', 0, 0, 'C')

def clean_text(text):
    """
    Sanitizes text for FPDF to prevent encoding errors.
    Replaces special symbols like Naira (₦) with 'N'.
    """
    if not isinstance(text, str): return str(text)
    
    # Replace known problem characters
    text = text.replace("₦", "N").replace("’", "'").replace("–", "-")
    
    # Remove Markdown bold markers (**text**)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    
    # Remove header markers (###)
    text = re.sub(r'### ', '', text)
    
    # Encode to latin-1 to make FPDF happy
    return text.encode('latin-1', 'ignore').decode('latin-1')

def generate_pdf_report(user_query, location, soil_type, ai_text, boq_dataframe, report_type="Standard"):
    """
    Generates a professional PDF report.
    Supports 'Standard' (Construction Estimate) and 'Bank' (Loan Valuation) formats.
    """
    pdf = PDFReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # --- 1. TITLE SECTION ---
    pdf.set_font("Arial", "B", 16)
    title = "CONSTRUCTION COST ESTIMATE" if report_type == "Standard" else "BANK LOAN VALUATION REPORT"
    pdf.cell(0, 10, title, ln=True, align='C')
    pdf.ln(5)
    
    # --- 2. META DATA ---
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 5, f"Location: {clean_text(location)}", ln=True)
    pdf.cell(0, 5, f"Soil Condition: {clean_text(soil_type)}", ln=True)
    
    if report_type == "Bank":
        pdf.cell(0, 5, "Purpose: Mortgage / Construction Loan Application", ln=True)
        pdf.cell(0, 5, "Valuation Standard: RICS / NIQS Guidelines", ln=True)
    pdf.ln(10)
    
    # --- 3. EXECUTIVE SUMMARY (AI TEXT) ---
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "1. EXECUTIVE SUMMARY & SCOPE", 0, 1, 'L', fill=True)
    pdf.set_font("Arial", size=10)
    
    # Strip unnecessary parts from AI text if present
    text_body = ai_text
    if "|||" in ai_text: text_body = ai_text.split("|||")[0]
    elif "4. Bill of Quantities" in ai_text: text_body = ai_text.split("4. Bill of Quantities")[0]
    
    pdf.ln(2)
    pdf.multi_cell(0, 5, clean_text(text_body.strip()))
    pdf.ln(10)
    
    # --- 4. FINANCIAL TABLES ---
    if boq_dataframe is not None and not boq_dataframe.empty:
        pdf.set_font("Arial", "B", 12)
        header_text = "2. BILL OF QUANTITIES" if report_type == "Standard" else "2. CAPITAL EXPENDITURE (CAPEX)"
        pdf.cell(0, 10, header_text, 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        # Table Header
        pdf.set_font("Arial", "B", 9)
        pdf.set_fill_color(255, 140, 0) # Orange Header
        pdf.set_text_color(255) # White Text
        
        pdf.cell(80, 8, "Item Description", 1, 0, 'L', 1)
        pdf.cell(20, 8, "Qty", 1, 0, 'C', 1)
        pdf.cell(40, 8, "Unit Cost (N)", 1, 0, 'R', 1)
        pdf.cell(50, 8, "Total (N)", 1, 1, 'R', 1)
        
        # Table Rows
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(0) # Black Text
        total_cost = 0
        
        for _, row in boq_dataframe.iterrows():
            item = clean_text(str(row['Item']))[:40] # Truncate long names
            qty = str(row['Qty'])
            unit = f"{row['Unit Price']:,.0f}"
            total = f"{row['Total Cost']:,.0f}"
            
            pdf.cell(80, 8, item, 1)
            pdf.cell(20, 8, qty, 1, 0, 'C')
            pdf.cell(40, 8, unit, 1, 0, 'R')
            pdf.cell(50, 8, total, 1, 1, 'R')
            total_cost += row['Total Cost']
            
        # Grand Total Row
        pdf.set_font("Arial", "B", 10)
        pdf.cell(140, 8, "GRAND TOTAL ESTIMATE", 1, 0, 'R')
        pdf.set_fill_color(200, 255, 200) # Light Green
        pdf.cell(50, 8, f"N {total_cost:,.0f}", 1, 1, 'R', fill=True)
    
    # --- 5. BANK SPECIFIC SECTION ---
    if report_type == "Bank":
        pdf.ln(10)
        pdf.set_font("Arial", "B", 12)
        pdf.set_fill_color(240, 240, 240)
        pdf.cell(0, 10, "3. RISK ASSESSMENT & DRAWDOWN", 0, 1, 'L', fill=True)
        
        pdf.set_font("Arial", size=10)
        pdf.ln(2)
        risk_text = (
            "The prices quoted herein reflect current market rates. We recommend a contingency fund "
            "of 15% due to inflationary trends in steel and cement prices.\n\n"
            "RECOMMENDED DRAWDOWN SCHEDULE:\n"
            "- Tranche A (Mobilization): 30%\n"
            "- Tranche B (Carcass/Roofing): 40%\n"
            "- Tranche C (Finishing): 30%"
        )
        pdf.multi_cell(0, 5, clean_text(risk_text))

    # --- DISCLAIMER ---
    pdf.ln(20)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(200, 0, 0) # Dark Red
    disclaimer = "DISCLAIMER: Generated by SiteMate Pro AI. This document serves as a preliminary estimate. Please consult a physical Quantity Surveyor for final certification."
    pdf.multi_cell(0, 5, clean_text(disclaimer))
    
    return pdf.output(dest='S').encode('latin-1')