from fpdf import FPDF
import pandas as pd
from datetime import datetime
import re

# --- HELPER: TEXT SANITIZER ---
def clean_text(text):
    """
    Sanitizes text for FPDF to prevent encoding errors.
    Replaces special symbols like Naira (₦) with 'N'.
    """
    if not isinstance(text, str): return str(text)
    
    # Replace known problem characters
    text = text.replace("₦", "N").replace("’", "'").replace("–", "-").replace("“", '"').replace("”", '"')
    
    # Remove Markdown bold markers (**text**)
    text = re.sub(r'\*\*(.*?)\*\*', r'\1', text)
    
    # Remove header markers (###)
    text = re.sub(r'### ', '', text)
    
    # Encode to latin-1 to make FPDF happy (strips unsupported unicode)
    return text.encode('latin-1', 'ignore').decode('latin-1')

# --- PDF CLASS ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 12)
        self.cell(0, 10, 'SiteMate Pro | Engineering Report', 0, 1, 'C')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.set_text_color(128)
        self.cell(0, 10, f'Generated by SiteMate Pro AI - Page {self.page_no()}', 0, 0, 'C')

# --- 1. BOQ / ESTIMATE REPORT ---
def generate_pdf_report(user_query, location, soil_type, ai_text, boq_dataframe, report_type="Standard"):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)
    
    # Title
    pdf.set_font("Arial", "B", 16)
    title = "CONSTRUCTION COST ESTIMATE" if report_type == "Standard" else "BANK LOAN VALUATION REPORT"
    pdf.cell(0, 10, title, ln=True, align='C')
    pdf.ln(5)
    
    # Meta Data
    pdf.set_font("Arial", size=10)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True)
    pdf.cell(0, 5, f"Location: {clean_text(location)}", ln=True)
    pdf.cell(0, 5, f"Soil Condition: {clean_text(soil_type)}", ln=True)
    
    if report_type == "Bank":
        pdf.cell(0, 5, "Purpose: Mortgage / Construction Loan Application", ln=True)
        pdf.cell(0, 5, "Valuation Standard: RICS / NIQS Guidelines", ln=True)
    pdf.ln(10)
    
    # Executive Summary
    pdf.set_fill_color(240, 240, 240)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "1. EXECUTIVE SUMMARY & SCOPE", 0, 1, 'L', fill=True)
    pdf.set_font("Arial", size=10)
    
    text_body = ai_text
    if "|||" in ai_text: text_body = ai_text.split("|||")[0]
    
    pdf.ln(2)
    pdf.multi_cell(0, 5, clean_text(text_body.strip()))
    pdf.ln(10)
    
    # BOQ Table
    if boq_dataframe is not None and not boq_dataframe.empty:
        pdf.set_font("Arial", "B", 12)
        header_text = "2. BILL OF QUANTITIES" if report_type == "Standard" else "2. CAPITAL EXPENDITURE (CAPEX)"
        pdf.cell(0, 10, header_text, 0, 1, 'L', fill=True)
        pdf.ln(2)
        
        pdf.set_font("Arial", "B", 9)
        pdf.set_fill_color(255, 140, 0) # Orange Header
        pdf.set_text_color(255) # White Text
        
        pdf.cell(80, 8, "Item Description", 1, 0, 'L', 1)
        pdf.cell(20, 8, "Qty", 1, 0, 'C', 1)
        pdf.cell(40, 8, "Unit Cost (N)", 1, 0, 'R', 1)
        pdf.cell(50, 8, "Total (N)", 1, 1, 'R', 1)
        
        pdf.set_font("Arial", size=9)
        pdf.set_text_color(0) # Black Text
        total_cost = 0
        
        for _, row in boq_dataframe.iterrows():
            item = clean_text(str(row['Item']))[:40]
            qty = str(row['Qty'])
            unit = f"{row['Unit Price']:,.0f}"
            total = f"{row['Total Cost']:,.0f}"
            
            pdf.cell(80, 8, item, 1)
            pdf.cell(20, 8, qty, 1, 0, 'C')
            pdf.cell(40, 8, unit, 1, 0, 'R')
            pdf.cell(50, 8, total, 1, 1, 'R')
            total_cost += row['Total Cost']
            
        pdf.set_font("Arial", "B", 10)
        pdf.cell(140, 8, "GRAND TOTAL ESTIMATE", 1, 0, 'R')
        pdf.set_fill_color(200, 255, 200) # Light Green
        pdf.cell(50, 8, f"N {total_cost:,.0f}", 1, 1, 'R', fill=True)
    
    # Disclaimer
    pdf.ln(20)
    pdf.set_font("Arial", "I", 8)
    pdf.set_text_color(200, 0, 0)
    disclaimer = "DISCLAIMER: Generated by SiteMate Pro AI. This document serves as a preliminary estimate. Please consult a physical Quantity Surveyor for final certification."
    pdf.multi_cell(0, 5, clean_text(disclaimer))
    
    return pdf.output(dest='S').encode('latin-1')

# --- 2. EXPENSE REPORT ---
def generate_expense_pdf(project_name, planned_total, expense_df):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"SITE EXECUTION LOGBOOK: {clean_text(project_name)}", ln=True, align='C')
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 5, f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    pdf.ln(10)

    spent = expense_df['amount'].sum() if not expense_df.empty else 0
    balance = planned_total - spent
    
    pdf.set_font("Arial", "B", 12)
    pdf.set_fill_color(240, 240, 240)
    pdf.cell(0, 10, "1. FINANCIAL STATUS", 0, 1, 'L', fill=True)
    
    pdf.set_font("Arial", size=10)
    pdf.ln(2)
    
    pdf.cell(50, 8, "Total Planned Budget:", 0)
    pdf.cell(50, 8, f"N {planned_total:,.2f}", 0, 1)
    
    pdf.cell(50, 8, "Total Actual Spent:", 0)
    pdf.set_text_color(200, 0, 0)
    pdf.cell(50, 8, f"N {spent:,.2f}", 0, 1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.cell(50, 8, "Remaining Balance:", 0)
    pdf.set_text_color(0, 150, 0)
    pdf.cell(50, 8, f"N {balance:,.2f}", 0, 1)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(5)

    pdf.set_font("Arial", "B", 12)
    pdf.cell(0, 10, "2. DAILY EXPENSE LOG", 0, 1, 'L', fill=True)
    pdf.ln(2)

    pdf.set_fill_color(230, 230, 230)
    pdf.set_font("Arial", "B", 9)
    pdf.cell(25, 8, "Date", 1, 0, 'C', 1)
    pdf.cell(30, 8, "Category", 1, 0, 'L', 1)
    pdf.cell(60, 8, "Item Description", 1, 0, 'L', 1)
    pdf.cell(35, 8, "Amount (N)", 1, 0, 'R', 1)
    pdf.cell(40, 8, "Note", 1, 1, 'L', 1)

    pdf.set_font("Arial", size=9)
    if not expense_df.empty:
        expense_df = expense_df.sort_values(by="date", ascending=False)
        for _, row in expense_df.iterrows():
            pdf.cell(25, 8, str(row['date']), 1)
            pdf.cell(30, 8, clean_text(str(row['category'])), 1)
            pdf.cell(60, 8, clean_text(str(row['item']))[:30], 1)
            pdf.cell(35, 8, f"{row['amount']:,.2f}", 1, 0, 'R')
            pdf.cell(40, 8, clean_text(str(row['note']))[:20], 1, 1)

    pdf.ln(20)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 10, "_"*60, ln=True)
    pdf.cell(0, 5, "Site Engineer Signature & Date", ln=True)

    return pdf.output(dest='S').encode('latin-1')

# --- 3. INVENTORY REPORT ---
def generate_inventory_pdf(project_name, inventory_df, history_df):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"INVENTORY AUDIT REPORT: {clean_text(project_name)}", ln=True, align='C')
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    pdf.ln(10)

    # Section 1: Current Status
    pdf.set_font("Arial", "B", 12)
    pdf.set_fill_color(0, 128, 0)
    pdf.set_text_color(255)
    pdf.cell(0, 10, "1. CURRENT STOCK LEVELS", 0, 1, 'L', fill=True)
    pdf.ln(2)
    
    pdf.set_fill_color(230, 230, 230)
    pdf.set_text_color(0)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(80, 8, "Material Item", 1, 0, 'L', 1)
    pdf.cell(40, 8, "Current Qty", 1, 0, 'C', 1)
    pdf.cell(30, 8, "Unit", 1, 0, 'C', 1)
    pdf.cell(40, 8, "Last Updated", 1, 1, 'C', 1)

    pdf.set_font("Arial", size=10)
    if not inventory_df.empty:
        for _, row in inventory_df.iterrows():
            pdf.cell(80, 8, clean_text(str(row['Item'])), 1)
            pdf.cell(40, 8, f"{row['Quantity']:.1f}", 1, 0, 'C')
            pdf.cell(30, 8, clean_text(str(row['Unit'])), 1, 0, 'C')
            pdf.cell(40, 8, str(row['Last Updated']), 1, 1, 'C')
    else:
        pdf.cell(0, 10, "No stock data available.", 1, 1, 'C')
    
    pdf.ln(10)

    # Section 2: History
    pdf.set_font("Arial", "B", 12)
    pdf.set_fill_color(70, 70, 70)
    pdf.set_text_color(255)
    pdf.cell(0, 10, "2. DAILY TRANSACTION LOG (IN/OUT)", 0, 1, 'L', fill=True)
    pdf.ln(2)

    pdf.set_fill_color(230, 230, 230)
    pdf.set_text_color(0)
    pdf.set_font("Arial", "B", 9)
    pdf.cell(25, 8, "Date", 1, 0, 'C', 1)
    pdf.cell(20, 8, "Time", 1, 0, 'C', 1)
    pdf.cell(60, 8, "Item", 1, 0, 'L', 1)
    pdf.cell(35, 8, "Action", 1, 0, 'C', 1)
    pdf.cell(25, 8, "Change", 1, 0, 'R', 1)
    pdf.cell(25, 8, "Unit", 1, 1, 'C', 1)

    pdf.set_font("Arial", size=9)
    if not history_df.empty:
        for _, row in history_df.iterrows():
            pdf.cell(25, 8, str(row['Date']), 1)
            pdf.cell(20, 8, str(row['Time']), 1)
            pdf.cell(60, 8, clean_text(str(row['Item']))[:30], 1)
            
            op = str(row['Action'])
            if "IN" in op: pdf.set_text_color(0, 128, 0)
            else: pdf.set_text_color(200, 0, 0)
            pdf.cell(35, 8, op, 1, 0, 'C')
            
            change = f"{row['Change']:+.1f}"
            pdf.cell(25, 8, change, 1, 0, 'R')
            
            pdf.set_text_color(0)
            pdf.cell(25, 8, clean_text(str(row['Unit'])), 1, 1, 'C')
    else:
        pdf.cell(0, 10, "No transactions recorded yet.", 1, 1, 'C')

    pdf.ln(20)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 10, "_"*60, ln=True)
    pdf.cell(0, 5, "Store Keeper Signature & Date", ln=True)

    return pdf.output(dest='S').encode('latin-1')

# --- 4. SITE DIARY REPORT ---
def generate_diary_pdf(project_name, diary_df):
    pdf = PDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    pdf.set_font("Arial", "B", 16)
    pdf.cell(0, 10, f"SITE DIARY & LABOR LOG: {clean_text(project_name)}", ln=True, align='C')
    pdf.set_font("Arial", "I", 10)
    pdf.cell(0, 5, f"Report Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    pdf.ln(10)

    pdf.set_font("Arial", "B", 12)
    pdf.set_fill_color(52, 152, 219)
    pdf.set_text_color(255)
    pdf.cell(0, 10, "DAILY PROGRESS LOG", 0, 1, 'L', fill=True)
    pdf.ln(2)

    pdf.set_fill_color(230, 230, 230)
    pdf.set_text_color(0)
    pdf.set_font("Arial", "B", 9)
    
    pdf.cell(25, 8, "Date", 1, 0, 'C', 1)
    pdf.cell(25, 8, "Weather", 1, 0, 'C', 1)
    pdf.cell(50, 8, "Labor Force", 1, 0, 'L', 1)
    pdf.cell(50, 8, "Work Accomplished", 1, 0, 'L', 1)
    pdf.cell(40, 8, "Issues/Delays", 1, 1, 'L', 1)

    pdf.set_font("Arial", size=8)
    if not diary_df.empty:
        for _, row in diary_df.iterrows():
            date = str(row['Date'])
            weather = clean_text(str(row['Weather']))
            labor = clean_text(str(row['Labor']))[:45]
            work = clean_text(str(row['Work Done']))[:45]
            issue = clean_text(str(row['Issues']))[:35]
            
            pdf.cell(25, 8, date, 1)
            pdf.cell(25, 8, weather, 1)
            pdf.cell(50, 8, labor, 1)
            pdf.cell(50, 8, work, 1)
            pdf.cell(40, 8, issue, 1, 1)
    else:
        pdf.cell(0, 10, "No diary entries recorded.", 1, 1, 'C')

    pdf.ln(20)
    pdf.set_font("Arial", "B", 10)
    pdf.cell(0, 10, "_"*60, ln=True)
    pdf.cell(0, 5, "Site Engineer Signature", ln=True)

    return pdf.output(dest='S').encode('latin-1')